---
title: "Blog của tôi"
email: minhhoangtranpt@example.com
description: >-
  Đây là blog cá nhân của tôi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minhhoangtranpt.github.io/blog" # the base hostname & protocol for your site
theme: jekyll-theme-cayman
---
