# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tên Blog Của Bạn
author: Tên Của Bạn
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Một mô tả ngắn gọn và hấp dẫn về blog của bạn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://your-username.github.io" # a base hostname & protocol for your site
twitter_username: your_twitter_handle
github_username:  your_username

# Build settings
# Xóa hoặc ghi chú lại dòng này
# theme: minima

# Thêm dòng này
remote_theme: pages-themes/cayman@v0.2.0

# Các thông tin khác của bạn
title: Blog Với Giao Diện Mới
author: Tên Của Bạn
description: "Blog của tôi giờ đã đẹp hơn rất nhiều!"
plugins:
  - jekyll-feed
